title: Voronoi Art Generator
description: An interactive way to generate art using Voronoi diagrams
#show_downloads: true
show_downloads: false
#google_analytics:
theme: jekyll-theme-cayman

# to toggle showing the github link:
#github:
#  is_project_page: false

#website: https://tycho-bear.github.io/voronoi

#site.url: https://tycho-bear.github.io/voronoi

baseurl: /voronoi

github:
  is_project_page: true
