title: Voronoi Art Generator
description: An interactive Voronoi art generator
show_downloads: true
#show_downloads: false
#google_analytics:
theme: jekyll-theme-cayman

# to toggle showing the github link:
#github:
#  is_project_page: false
